"""add display_name

Revision ID: 20b03824cc2a
Revises: 8f1b3e945c2a
Create Date: 2026-05-23 18:22:28.151874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b03824cc2a'
down_revision: Union[str, Sequence[str], None] = '8f1b3e945c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_configs', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_configs', 'display_name')
    # ### end Alembic commands ###
