"""add_teams_and_leads

Revision ID: 629fb2d01dc2
Revises: 63cf4a43ba3b
Create Date: 2026-05-24 10:41:05.810754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629fb2d01dc2'
down_revision: Union[str, Sequence[str], None] = '63cf4a43ba3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_users_team', 'teams', ['team_id'], ['id'])
    op.execute("PRAGMA foreign_keys=ON")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_team', type_='foreignkey')
        batch_op.drop_column('team_id')
    # ### end Alembic commands ###
