"""add gmaps integration

Revision ID: 63cf4a43ba3b
Revises: 20b03824cc2a
Create Date: 2026-05-23 20:42:29.708029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cf4a43ba3b'
down_revision: Union[str, Sequence[str], None] = '20b03824cc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('latitude', sa.JSON(), nullable=True))
    op.add_column('businesses', sa.Column('longitude', sa.JSON(), nullable=True))
    op.add_column('businesses', sa.Column('google_maps_url', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('formatted_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'formatted_address')
    op.drop_column('businesses', 'google_maps_url')
    op.drop_column('businesses', 'longitude')
    op.drop_column('businesses', 'latitude')
    # ### end Alembic commands ###
